### ISSUE TITLE
Bug is docker version - WHOIS backup not working

### ISSUE THREAD

**Issue by ghost** [MarkBaggett/domain_stats#30]
Greetings!

I've been using domain_stats for some time and I love it. I've deployed it on docker version.
As far as I understand - to fix missing RDAP queries from WHOIS - I've should use command:
`docker exec -it domain_stats`
and then inside container
`domain-stats-utils -f /host_mounted_dir/`

Unfortunetly it throws error:
`Traceback (most recent call last):
  File "/usr/local/bin/domain-stats-utils", line 11, in <module>
    load_entry_point('domain-stats==1.0.1', 'console_scripts', 'domain-stats-utils')()
  File "/usr/local/lib/python3.6/dist-packages/domain_stats/utils.py", line 177, in main
    written += whois_patch_domain(domain, val.get("alerts"), val.get("freq"),)
  File "/usr/local/lib/python3.6/dist-packages/domain_stats/utils.py", line 96, in whois_patch_domain
    until_expires = (expires - now).total_seconds()
TypeError: can't subtract offset-naive and offset-aware datetimes`

How can I mitigate this?

And can you explain, WHOIS backup should be automaticly done by the engine or only manually by me using this command?

**Comment by willemri** [comment]
Hello, i've followed the SANS ondemand course of the python course and ran into the same issue. 
The fix would be add some lines in the utils.py. The issue resides, that the timezone is not fetched:

replace line 70:
now = datetime.datetime.now(datetime.timezone.utc)

replace line 87-88 with:

    if created.tzinfo is None:
        created = created.replace(tzinfo=datetime.timezone.utc)
    try:
      domain_age_seconds = (now - created).total_seconds()
    except Exception as e:
      if args.verbose: print(f"Error retrieving WHOIS record for {domain}: {e}")
