### ISSUE TITLE
whois query is not working

### ISSUE THREAD

**Issue by tbennett6421** [MarkBaggett/domain_stats#6]
Running Python 2.7.12 on a Ubuntu 16.04.3 LTS server.

root@soc:~/ python domain_stats.py -ip 127.0.0.1 -vv --alexa top-1m.csv 8000
```
Preloading 1000 alexa cache
Now preloading 1000 domains from alexa in the whois cache.
Server is Ready. http://127.0.0.1:8000/cmd/[subcmd/,]target
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "domain_stats.py", line 166, in preload_domains
    if args.verbose: server.safe_print("Error querying whois server: %s" % (str(e)))
NameError: global name 'args' is not defined

Server is Ready. http://127.0.0.1:8000/cmd/[subcmd/,]target
```

root@soc$ curl http://127.0.0.1:8000/domain/sans.org
root@soc$ [empty response]

```
Server is Ready. http://127.0.0.1:8000/cmd/[subcmd/,]target

/domain/sans.org
Querying the web sans.org
Error querying whois server: 'module' object has no attribute 'whois'
```

**Comment by tbennett6421** [comment]
Not sure what happened, but a deploy on a fresh 16.04 worked.

Ended up doing pip list, and then upgrading all the pip packages of a less < version. Removed repo, cloned and it's working now

**Comment by MarkBaggett** [comment]
Excellent.  Thanks for the update.
